# Generated by Django 5.0.6 on 2024-09-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='series_images/')),
                ('country', models.CharField(choices=[('TH', 'ไทย'), ('KR', 'เกาหลี'), ('CN', 'จีน')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
