# Generated by Django 5.0.6 on 2024-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_series_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='series',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
